### ISSUE TITLE
ISSUE: Node not working now - Youtube is blocking IP addresses for this scraper

### ISSUE THREAD

**Issue by kaptainkangaroo** [hapheus/n8n-nodes-youtube-transcript#1]
The node was working for me 2 days ago. But stopped working now. I believe its because Youtube is blocking IPs for scraping. 

possibly related to this: https://github.com/adnjoo/fast-youtube-summary/issues/26

Here is the error log. 
{
  "errorMessage": "Internal error",
  "errorDetails": {
    "rawErrorMessage": [
      "[YoutubeTranscript] 🚨 Impossible to retrieve Youtube video ID."
    ]
  },
  "n8nDetails": {
    "nodeName": "Youtube Transcript1",
    "nodeType": "n8n-nodes-youtube-transcript.youtubeTranscriptNode",
    "nodeVersion": 1,
    "itemIndex": 0,
    "time": "8/22/2024, 2:55:11 PM",
    "n8nVersion": "1.54.4 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeOperationError: [YoutubeTranscript] 🚨 Impossible to retrieve Youtube video ID.",
      "    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-youtube-transcript/nodes/YoutubeTranscriptNode/YoutubeTranscriptNode.node.ts:89:12)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1104:20"
    ]
  }
}

**Comment by hapheus** [comment]
Thanks for the hint. I'll have a look at it

**Comment by dasanworld** [comment]
How do I download other languages?

**Comment by alexandrexgoulart** [comment]
> Thanks for the hint. I'll have a look at it

Hello hapheus, how is it going ? do you have any good news about your node ?

**Comment by sdcharly** [comment]
i tried the latest 0.6.0 also.. same issue.

**Comment by hapheus** [comment]
Changed to a different package in version 0.7.1

**Comment by alexandrexgoulart** [comment]
> Changed to a different package in version 0.7.1

Here it continues the same error.

![image](https://github.com/user-attachments/assets/656b97bb-4dbe-4626-971a-ce67ed0c618b)

**Comment by hapheus** [comment]
The new version should have a fields for language and fallback language. Did you restart your n8n instance after updating?

<img width="1530" alt="image" src="https://github.com/user-attachments/assets/4e9b905f-81f2-444d-9ea2-06110a33ec77">

**Comment by alexandrexgoulart** [comment]
![image](https://github.com/user-attachments/assets/4b889637-4f69-414e-815d-c81df34e3048)
I restarted n8n self hosted and still an error.

**Comment by alexandrexgoulart** [comment]
> The new version should have a fields for language and fallback language. Did you restart your n8n instance after updating?
> 
> <img alt="image" width="1530" src="https://private-user-images.githubusercontent.com/837072/379394622-4e9b905f-81f2-444d-9ea2-06110a33ec77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MTE0ODEsIm5iZiI6MTcyOTcxMTE4MSwicGF0aCI6Ii84MzcwNzIvMzc5Mzk0NjIyLTRlOWI5MDVmLTgxZjItNDQ0ZC05ZWEyLTA2MTEwYTMzZWM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxOTE5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTc4ZDg5NjVhNDQ5ZDU3NDY3MWM0NjE0MzU4MzlkZjk2YzU5ZGU4YTFmYTAyZjliOTM2YWIwYzI3MjAxYjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rwnaH62wyyaDzS1MHLTHyLdnA2F4JmU7eJRiwKX_PP0">

I will reinstall my n8n, I think there are some folders missing.

**Comment by painteau** [comment]
Hello !

I updated to last version too. I restarted my dockerized n8n instance too.

I get the same error.

@alexandrexgoulart If you get some good result with a total reinstall, tell us and I will try and let you know too.


![chrome_2024-10-24_13-16-52](https://github.com/user-attachments/assets/9f8c76c6-7a7b-4f82-8ee7-5ad72ee7bffa)

**Comment by hapheus** [comment]
The new version (0.8.0) uses `puppeteer` with `stealth-plugin`, that uses the real browser in headless mode.
